[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
requires = [
    'requests > 0',
    'pandas > 0',
    'pydantic > 0',
    'xmltodict > 0'
]